<?php
// phpcs:ignoreFile -- WordPress block metadata files use the index.asset.php filename generated by the block tooling.
/**
 * Search block editor script metadata.
 *
 * @package BibliaDigitalWP
 */

return array(
	'dependencies' => array(
		'wp-block-editor',
		'wp-blocks',
		'wp-components',
		'wp-element',
		'wp-i18n',
	),
	'version'      => '1.1.43',
);
